### ISSUE TITLE
Wrong info in infra/bib.tex

### ISSUE THREAD

**Issue by elogy** [fsi-tue/anfiheft#13]
The information inside `bib.tex` is outdated, especially concerning the Sand Bib.
- There's still mention of "Grundstudium" inside this file (Jeez, this is old stuff)
- There's no old exams on the second door to the left anymore
- You can access the Bib using your student ID, this is not reflected
- Most stuff is not "Präsenzbestand" anymore and can be borrowed using the terminal on the front desk

**Comment by PhictionalOne** [comment]
Am I stupid or is this file no longer used in the last versions of the **anfiheft**?
As is it is not used in `anfiheft.tex` at least I could not find any reference or `\input`-commands linking to file in question.

**Comment by PhictionalOne** [comment]
I took a dive into the files and found the mention the *Bibs* in [`infrastruktur.tex`](../tree/master/info/uni/infrastruktur.tex).

Question is if it has the same misinformation in it?

**Comment by primeos** [comment]
> Am I stupid or is this file no longer used in the last versions of the anfiheft?

I also didn't find any reference ;) The last one was removed at the end of 2016 (commit 4ab3da8e0c67ffef325f4cc28942dac030c2a85a of the private history).

We can remove `bib.tex` then (and maybe merge some of its content first).

**Comment by PhictionalOne** [comment]
Can be removed. All of its contents were copy-pasted into `{info|kogni}/infrastruktur.tex` and has since been updated independently.
