### ISSUE TITLE
Add Kneipen- und "Kultur"-führer

### ISSUE THREAD

**Issue by Pfonks** [fsi-tue/anfiheft#18]
Create SQL-Table with places,
generate LaTeX through CSV or something like that [TeX from CSV](https://texblog.org/2012/05/30/generate-latex-tables-from-csv-files-excel/)

**Comment by PhictionalOne** [comment]
There is a concept in development.
Take a look at this [Overleaf snippet](https://www.overleaf.com/read/ptwmbtvvbvzv) (only view)

> **Note** that the csv file has to separate its content with pipe ("|") instead of comma (",")

A possible layout could be this
>![image](https://user-images.githubusercontent.com/24623459/73141701-488a3080-4087-11ea-94aa-8c2c7b6e4b81.png)
Any likeness to actual places is pure coincidence and should be treated as *Lorem ipsum*

**Comment by PhictionalOne** [comment]
@elogy Tex stuff is basically done. 
Now its time for somekind of actual Interface which produces the ominous csv

**Comment by elogy** [comment]
I'm on it.
![Bildschirmfoto vom 2020-01-27 00-03-00](https://user-images.githubusercontent.com/9336883/73143274-6ca23d80-4098-11ea-9433-1e211d03da0e.png)

**Comment by elogy** [comment]
@PhictionalOne I added yo as a collaborator so you can have a peek at what I'm cobbling together there ;)
