### ISSUE TITLE
Update to SoSe 21

### ISSUE THREAD

**Issue by PhictionalOne** [fsi-tue/anfiheft#25]
- [x] Neue [Profs](https://uni-tuebingen.de/de/139980) in `adressen.tex` eintragen
- [x] Überprüfen ob links noch alle tun
- [x] Corona Disclaimer umschreiben
    - [x] `fachschaften.tex` Sitzungszeit dazupacken
    - [x] `erste_wochen.tex` Kogni-Streichen/Erstiveranstaltungen
    - [x] `mensen.tex` ??/Umschreiben
    - [x] `hochschulsport.tex` WS → SS
    - [x] `unikino.tex` WS→ SS

**Comment by NoRyyZ** [comment]
- [ ] Evtl. PPI mit einem Satz mehr erläutern (das Prinzip Protokolle schreiben für mehr Protokolle downloaden)?
- [ ] Link 26, Seite 29 funktioniert nicht mehr: "https://uni-tuebingen.de/fileadmin/Uni_Tuebingen/Einrichtungen/ZDV/Dokumente/Anleitungen/eduroam/eduroam-uni-tuebingen.mobileconfig"

Ich hab alle Links mal angeklickt und die haben aus meiner Sicht gepasst. Sonst ist mir nur das aufgefallen, was oben schon genannt wurde. - Moritz

**Comment by PhictionalOne** [comment]
See #26
