### ISSUE TITLE
Content Update WS21

### ISSUE THREAD

**Issue by PhictionalOne** [fsi-tue/anfiheft#27]
Like every semester it is this time again!

### Was muss man machen?
- [x] Neue Profs in 'adressen.tex' eintragen
- [x] Überprüfen ob die Links noch tun
- [x] Corona Disclaimer umschreiben
- Folgende Dateien angucken:
    - [x] 'fachschaften.tex'
    - [x] 'erste_wochen.tex'
    - [x] 'mensen.tex'
    - [x] 'hochschulsport.tex', 'unikino.tex', ... (an Uni angegliedertes)
- [x] **WICHTIG** Beispielstudienpläne auf neue PO umändern
    - [x] Vorlesungen aufs neue *Naming Scheme* umfassen
    - [x] Neue Module eintragen
    - [x] Im sonstigen Fließtext ausbessern

**Comment by PhictionalOne** [comment]
> **WICHTIG** Beispielstudienpläne auf neue PO umändern
- [ ] Lehramt fehlt noch

**Comment by PhictionalOne** [comment]
- [ ] Update Kogni-Mentoren/StudBeratung

**Comment by luoe** [comment]
Thanks :heart:
